export type ExerciseSeed = {
  id: number;
  name: string;
  complexity: number;
  musclesTargeted: {
    name: string;
    impact: number;
  }[];
  timePerRepInS: number;
  blocks: string[];
};

export const exercisesSeed = {
  1: {
    id: 1,
    name: 'Deadlift',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'coxa anterior', impact: 3 },
      { name: 'costas inferior', impact: 4 },
      { name: 'gluteos', impact: 4 },
      { name: 'abdominal', impact: 1 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD', 'Skill'],
  },
  2: {
    id: 2,
    name: 'Front Squat',
    complexity: 2,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa anterior', impact: 5 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'gluteos', impact: 3 },
      { name: 'costas inferior', impact: 2 },
      { name: 'abdominal', impact: 2 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD', 'Skill', 'Warm up'],
  },
  3: {
    id: 3,
    name: 'Back Squat',
    complexity: 2,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa posterior', impact: 4 },
      { name: 'gluteos', impact: 3 },
      { name: 'abdominal', impact: 2 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD', 'Skill', 'Warm Up'],
  },
  4: {
    id: 4,
    name: 'Hip Thrust',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 2 },
      { name: 'gluteos', impact: 5 },
      { name: 'abdominal', impact: 3 },
      { name: 'coxa anterior', impact: 2 },
      { name: 'coxa posterior', impact: 3 },
    ],
    timePerRepInS: 2.5,
    blocks: ['WOD', 'Skill', 'Warm Up'],
  },
  5: {
    id: 5,
    name: 'Bench Press',
    complexity: 2,
    musclesTargeted: [
      // { name: "cardio", impact: 2 },
      { name: 'peito', impact: 5 },
      { name: 'triceps', impact: 4 },
      { name: 'ombro', impact: 3 },
      { name: 'costas superior', impact: 1 },
    ],
    timePerRepInS: 2.5,
    blocks: ['WOD', 'Skill'],
  },
  6: {
    id: 6,
    name: 'Push Press',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'ombro', impact: 5 },
      { name: 'triceps', impact: 2 },
      { name: 'costas superior', impact: 2 },
      { name: 'peito', impact: 1 },
    ],
    timePerRepInS: 2.5,
    blocks: ['WOD', 'Skill'],
  },
  7: {
    id: 7,
    name: 'Shoulder Press',
    complexity: 2,
    musclesTargeted: [
      { name: 'ombro', impact: 5 },
      { name: 'costas superior', impact: 1 },
      { name: 'triceps', impact: 3 },
      // { name: "cardio", impact: 2 },
    ],
    timePerRepInS: 2.5,
    blocks: ['WOD', 'Skill'],
  },
  8: {
    id: 8,
    name: 'Overhead Squat',
    complexity: 3,
    musclesTargeted: [
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 4 },
      { name: 'ombro', impact: 3 },
      { name: 'abdominal', impact: 2 },
      // { name: "cardio", impact: 3 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD', 'Skill'],
  },
  9: {
    id: 9,
    name: 'Snatch Pull',
    complexity: 3,
    musclesTargeted: [
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 4 },
      { name: 'ombro', impact: 4 },
      { name: 'costas superior', impact: 2 },
      // { name: "cardio", impact: 3 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD', 'Skill'],
  },
  10: {
    id: 10,
    name: 'Clean Pull',
    complexity: 3,
    musclesTargeted: [
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 4 },
      { name: 'ombro', impact: 4 },
      { name: 'costas superior', impact: 2 },
      // { name: "cardio", impact: 3 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD', 'Skill'],
  },
  11: {
    id: 11,
    name: 'Overhead Lunges',
    complexity: 3,
    musclesTargeted: [
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 4 },
      { name: 'ombro', impact: 3 },
      { name: 'abdominal', impact: 2 },
      // { name: "cardio", impact: 3 },
    ],
    timePerRepInS: 4,
    blocks: ['WOD', 'Skill', 'Warm Up'],
  },
  12: {
    id: 12,
    name: 'Thruster',
    complexity: 3,
    musclesTargeted: [
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 4 },
      { name: 'ombro', impact: 4 },
      { name: 'triceps', impact: 3 },
      { name: 'abdominal', impact: 1 },
      // { name: "cardio", impact: 3 },
    ],
    timePerRepInS: 3.5,
    blocks: ['WOD', 'Skill'],
  },
  13: {
    id: 13,
    name: 'Cluster',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 4 },
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 4 },
      { name: 'ombro', impact: 4 },
      { name: 'costas superior', impact: 3 },
      { name: 'triceps', impact: 2 },
    ],
    timePerRepInS: 3.5,
    blocks: ['WOD', 'Skill'],
  },
  14: {
    id: 14,
    name: 'American Swing',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'gluteos', impact: 3 },
      { name: 'ombro', impact: 3 },
      { name: 'costas inferior', impact: 2 },
    ],
    timePerRepInS: 2,
    blocks: ['Skill', 'WOD'],
  },
  15: {
    id: 15,
    name: 'Russian Swing',
    complexity: 2,
    musclesTargeted: [
      // { name: "cardio", impact: 4 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'gluteos', impact: 3 },
      { name: 'ombro', impact: 2 },
      { name: 'costas inferior', impact: 2 },
    ],
    timePerRepInS: 2,
    blocks: ['Skill', 'WOD'],
  },
  16: {
    id: 16,
    name: 'Sumo Deadlift High Pull',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa posterior', impact: 5 },
      { name: 'ombro', impact: 4 },
      { name: 'costas superior', impact: 2 },
      { name: 'gluteos', impact: 3 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD', 'Skill'],
  },
  17: {
    id: 17,
    name: 'Globet Squat',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa anterior', impact: 3 },
      { name: 'coxa posterior', impact: 4 },
      { name: 'gluteos', impact: 3 },
      { name: 'abdominal', impact: 1 },
      { name: 'costas inferior', impact: 1 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD', 'Skill', 'Warm up'],
  },
  18: {
    id: 18,
    name: 'Bulgarian Split Squat',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 2 },
      { name: 'coxa anterior', impact: 5 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'gluteos', impact: 4 },
      { name: 'abdominal', impact: 1 },
      { name: 'costas inferior', impact: 1 },
    ],
    timePerRepInS: 2.5,
    blocks: ['WOD', 'Skill'],
  },
  19: {
    id: 19,
    name: 'Dumbbell Snatch',
    complexity: 3,

    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'coxa anterior', impact: 2 },
      { name: 'ombro', impact: 3 },
      { name: 'triceps', impact: 1 },
      { name: 'costas superior', impact: 2 },
      { name: 'gluteos', impact: 2 },
    ],
    timePerRepInS: 3,
    blocks: ['Skill', 'WOD'],
  },
  20: {
    id: 20,
    name: 'Dumbbell Snatch Lunge',
    complexity: 4,

    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa anterior', impact: 3 },
      { name: 'coxa posterior', impact: 2 },
      { name: 'ombro', impact: 3 },
      { name: 'triceps', impact: 1 },
      { name: 'costas superior', impact: 2 },
      { name: 'gluteos', impact: 2 },
      { name: 'abdominal', impact: 1 },
    ],
    timePerRepInS: 3,
    blocks: ['Skill', 'WOD'],
  },
  21: {
    id: 21,
    name: 'Dumbbell Clean',
    complexity: 3,

    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa anterior', impact: 3 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'costas superior', impact: 2 },
      { name: 'ombro', impact: 2 },
      { name: 'biceps', impact: 2 },
      { name: 'triceps', impact: 1 },
      { name: 'costas inferior', impact: 2 },
      { name: 'gluteos', impact: 3 },
    ],
    timePerRepInS: 3,
    blocks: ['Skill', 'WOD'],
  },
  22: {
    id: 22,
    name: 'Dumbbell Hang Clean AND Jerk',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa anterior', impact: 3 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'costas superior', impact: 2 },
      { name: 'ombro', impact: 3 },
      { name: 'biceps', impact: 2 },
      { name: 'triceps', impact: 2 },
      { name: 'costas inferior', impact: 2 },
      { name: 'gluteos', impact: 3 },
    ],
    timePerRepInS: 4,
    blocks: ['WOD', 'Skill'],
  },
  23: {
    id: 23,
    name: 'DEVIL PRESS',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 5 },
      { name: 'coxa anterior', impact: 3 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'peito', impact: 4 },
      { name: 'ombro', impact: 4 },
      { name: 'panturrilha', impact: 2 },
      { name: 'biceps', impact: 2 },
      { name: 'triceps', impact: 2 },
      { name: 'abdominal', impact: 2 },
      { name: 'gluteos', impact: 3 },
      { name: 'costas inferior', impact: 2 },
    ],
    timePerRepInS: 4,
    blocks: ['WOD', 'Skill'],
  },
  24: {
    id: 24,
    name: 'MAN MAKER',
    complexity: 4,
    musclesTargeted: [
      // { name: "cardio", impact: 4 },
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 4 },
      { name: 'peito', impact: 4 },
      { name: 'ombro', impact: 4 },
      { name: 'panturrilha', impact: 2 },
      { name: 'biceps', impact: 3 },
      { name: 'triceps', impact: 3 },
      { name: 'abdominal', impact: 3 },
      { name: 'gluteos', impact: 3 },
      { name: 'costas inferior', impact: 3 },
    ],
    timePerRepInS: 6,
    blocks: ['WOD', 'Skill'],
  },
  25: {
    id: 25,
    name: 'Wall Ball',
    complexity: 4,
    musclesTargeted: [
      // { name: "cardio", impact: 4 },
      { name: 'coxa anterior', impact: 5 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'abdominal', impact: 1 },
      { name: 'ombro', impact: 4 },
      { name: 'gluteos', impact: 3 },
      { name: 'costas superior', impact: 2 },
    ],
    timePerRepInS: 2,
    blocks: ['Skill', 'WOD'],
  },
  26: {
    id: 26,
    name: 'Strict Pull/C2B',
    complexity: 2,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'costas superior', impact: 5 },
      { name: 'biceps', impact: 3 },
    ],
    timePerRepInS: 2,
    blocks: ['Skill', 'WOD'],
  },
  27: {
    id: 27,
    name: 'Strict Hand Stand Push Ups',
    complexity: 4,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'ombro', impact: 5 },
      { name: 'costas superior', impact: 3 },
      { name: 'triceps', impact: 3 },
    ],
    timePerRepInS: 2,
    blocks: ['Skill', 'WOD'],
  },
  28: {
    id: 28,
    name: 'Strict Ring Dip',
    complexity: 2,
    musclesTargeted: [
      // { name: "cardio", impact: 2 },
      { name: 'peito', impact: 4 },
      { name: 'triceps', impact: 4 },
      { name: 'costas superior', impact: 2 },
    ],
    timePerRepInS: 2.5,
    blocks: ['Skill', 'WOD'],
  },
  29: {
    id: 29,
    name: 'peito to Bar',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 2 },
      { name: 'costas superior', impact: 4 },
      { name: 'biceps', impact: 4 },
    ],
    timePerRepInS: 2,
    blocks: ['Skill', 'WOD'],
  },
  // 30: {
  //   id: 30,
  //   name: "Pull Up",
  //   complexity: 2,
  //   musclesTargeted: [
  // //     { name: "cardio", impact: 1 },
  //     { name: "coxa posterior", impact: 1 },
  //     { name: "costas superior", impact: 4 },
  //     { name: "biceps", impact: 3 },
  //     { name: "abs", impact: 1 },
  //   ],
  //   timePerRepInS: 2,
  //   blocks: ["WOD", "Skill"],
  // },
  31: {
    id: 31,
    name: 'Ring Row',
    complexity: 1,
    musclesTargeted: [
      // { name: "cardio", impact: 1 },
      { name: 'coxa posterior', impact: 1 },
      { name: 'costas superior', impact: 3 },
      { name: 'biceps', impact: 2 },
      { name: 'abdominal', impact: 1 },
    ],
    timePerRepInS: 2,
    blocks: ['Warm Up', 'Skill'],
  },
  32: {
    id: 32,
    name: 'Hand Stand Push Ups',
    complexity: 5,
    musclesTargeted: [
      // { name: "cardio", impact: 2 },
      { name: 'ombro', impact: 5 },
      { name: 'costas superior', impact: 3 },
      { name: 'triceps', impact: 3 },
      { name: 'abdominal', impact: 1 },
    ],
    timePerRepInS: 2,
    blocks: ['WOD', 'Skill'],
  },
  33: {
    id: 33,
    name: 'Push Up',
    complexity: 1,
    musclesTargeted: [
      // { name: "cardio", impact: 2 },
      { name: 'peito', impact: 4 },
      { name: 'ombro', impact: 3 },
      { name: 'triceps', impact: 2 },
      { name: 'abdominal', impact: 1 },
    ],
    timePerRepInS: 1.5,
    blocks: ['Warm Up', 'WOD', 'Skill'],
  },
  34: {
    id: 34,
    name: 'Air Squat',
    complexity: 1,
    musclesTargeted: [
      // { name: "cardio", impact: 2 },
      { name: 'coxa anterior', impact: 3 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'gluteos', impact: 3 },
      { name: 'abdominal', impact: 1 },
    ],
    timePerRepInS: 1.5,
    blocks: ['Warm Up', 'WOD', 'Skill'],
  },
  35: {
    id: 35,
    name: 'Lunge',
    complexity: 2,
    musclesTargeted: [
      // { name: "cardio", impact: 2 },

      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 4 },
      { name: 'gluteos', impact: 3 },
      { name: 'abdominal', impact: 1 },
    ],
    timePerRepInS: 2.5,
    blocks: ['Warm Up', 'WOD', 'Skill'],
  },
  36: {
    id: 36,
    name: 'Bar Muscle Up',
    complexity: 5,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },

      { name: 'ombro', impact: 4 },
      { name: 'biceps', impact: 3 },
      { name: 'costas inferior', impact: 2 },
      { name: 'peito', impact: 3 },
    ],
    timePerRepInS: 3.5,
    blocks: ['WOD', 'Skill'],
  },
  37: {
    id: 37,
    name: 'Ring Muscle Up',
    complexity: 5,
    musclesTargeted: [
      // { name: "cardio", impact: 4 },

      { name: 'ombro', impact: 5 },
      { name: 'biceps', impact: 4 },
      { name: 'costas inferior', impact: 2 },
      { name: 'abdominal', impact: 2 },
      { name: 'peito', impact: 4 },
    ],
    timePerRepInS: 3.5,
    blocks: ['WOD', 'Skill'],
  },
  38: {
    id: 38,
    name: 'Pistol',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 2 },

      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 4 },
      { name: 'gluteos', impact: 4 },
      { name: 'abdominal', impact: 2 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD', 'Skill'],
  },
  39: {
    id: 39,
    name: 'Handstand Walk',
    complexity: 4,
    musclesTargeted: [
      // { name: "cardio", impact: 2 },

      { name: 'ombro', impact: 5 },
      { name: 'triceps', impact: 3 },
      { name: 'costas superior', impact: 3 },
      { name: 'abdominal', impact: 2 },
    ],
    timePerRepInS: 1,
    blocks: ['WOD', 'Skill'],
  },
  40: {
    id: 40,
    name: 'Rope Climb/Legless',
    complexity: 4,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },

      { name: 'biceps', impact: 4 },
      { name: 'costas superior', impact: 3 },
      { name: 'ombro', impact: 3 },
      { name: 'abdominal', impact: 3 },
      { name: 'costas inferior', impact: 2 },
    ],
    timePerRepInS: 1,
    blocks: ['WOD', 'Skill'],
  },
  41: {
    id: 41,
    name: 'Toes to Bar',
    complexity: 3,

    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'abdominal', impact: 4 },
      { name: 'costas superior', impact: 1 },
    ],
    timePerRepInS: 2,
    blocks: ['WOD', 'Skill'],
  },
  42: {
    id: 42,
    name: 'Box Jump Over',
    complexity: 2,

    musclesTargeted: [
      // { name: "cardio", impact: 4 },
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'gluteos', impact: 2 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD', 'Skill'],
  },
  43: {
    id: 43,
    name: 'Box Jump',
    complexity: 2,

    musclesTargeted: [
      // { name: "cardio", impact: 4 },
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'gluteos', impact: 2 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD', 'Skill'],
  },
  44: {
    id: 44,
    name: 'Burpee Box Jump Over',
    complexity: 3,

    musclesTargeted: [
      // { name: "cardio", impact: 5 },
      { name: 'coxa anterior', impact: 4 },
      { name: 'gluteos', impact: 2 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'abdominal', impact: 1 },
      { name: 'ombro', impact: 1 },
      { name: 'peito', impact: 3 },
    ],
    timePerRepInS: 4,
    blocks: ['WOD'],
  },
  45: {
    id: 45,
    name: 'Burpee Box Jump',
    complexity: 3,

    musclesTargeted: [
      // { name: "cardio", impact: 5 },
      { name: 'coxa anterior', impact: 4 },
      { name: 'gluteos', impact: 2 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'abdominal', impact: 1 },
      { name: 'ombro', impact: 1 },
      { name: 'peito', impact: 3 },
    ],
    timePerRepInS: 4,
    blocks: ['WOD'],
  },
  46: {
    id: 46,
    name: 'Burpee Over Bar',
    complexity: 3,

    musclesTargeted: [
      // { name: "cardio", impact: 5 },
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'peito', impact: 3 },
      { name: 'gluteos', impact: 2 },
      { name: 'abdominal', impact: 1 },
      { name: 'ombro', impact: 1 },
    ],
    timePerRepInS: 4,
    blocks: ['WOD'],
  },
  47: {
    id: 47,
    name: 'Step Up Over Box',
    complexity: 2,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa anterior', impact: 3 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'gluteos', impact: 2 },
      { name: 'panturrilha', impact: 2 },
      { name: 'costas inferior', impact: 1 },
      { name: 'abdominal', impact: 1 },
    ],
    timePerRepInS: 2.5,
    blocks: ['WOD', 'Skill'],
  },
  48: {
    id: 48,
    name: 'Step Up',
    complexity: 1,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa anterior', impact: 3 },
      { name: 'coxa posterior', impact: 3 },
      { name: 'gluteos', impact: 2 },
      { name: 'panturrilha', impact: 2 },
      { name: 'costas inferior', impact: 1 },
      { name: 'abdominal', impact: 1 },
    ],
    timePerRepInS: 1.5,
    blocks: ['Warm Up', 'WOD', 'Skill'],
  },
  49: {
    id: 49,
    name: 'Sit Up',
    complexity: 1,
    musclesTargeted: [
      // { name: "cardio", impact: 2 },
      { name: 'abdominal', impact: 5 },
    ],
    timePerRepInS: 2,
    blocks: ['Warm Up', 'WOD', 'Skill'],
  },
  50: {
    id: 50,
    name: 'V Up',
    complexity: 2,
    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'abdominal', impact: 5 },
      { name: 'coxa anterior', impact: 1 },
    ],
    timePerRepInS: 1.5,
    blocks: ['Skill', 'WOD'],
  },
  51: {
    id: 51,
    name: 'Clean',
    complexity: 4,
    musclesTargeted: [
      // { name: "cardio", impact: 4 },
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 4 },
      { name: 'gluteos', impact: 3 },
      { name: 'ombro', impact: 2 },
      { name: 'abdominal', impact: 1 },
      { name: 'costas inferior', impact: 3 },
    ],
    timePerRepInS: 3.5,
    blocks: ['WOD', 'Skill'],
  },
  52: {
    id: 52,
    name: 'Squat Clean',
    complexity: 4,
    musclesTargeted: [
      // { name: "cardio", impact: 4 },
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 4 },
      { name: 'gluteos', impact: 3 },
      { name: 'ombro', impact: 2 },
      { name: 'abdominal', impact: 1 },
      { name: 'costas inferior', impact: 3 },
    ],
    timePerRepInS: 3.5,
    blocks: ['WOD', 'Skill'],
  },
  53: {
    id: 53,
    name: 'Hang Clean',
    complexity: 3,
    musclesTargeted: [
      { name: 'ombro', impact: 4 },
      { name: 'panturrilha', impact: 1 },
      { name: 'biceps', impact: 2 },
      { name: 'triceps', impact: 2 },
      // { name: "cardio", impact: 2 },
      { name: 'costas inferior', impact: 2 },
    ],
    timePerRepInS: 3,
    blocks: ['Skill', 'WOD'],
  },
  54: {
    id: 54,
    name: 'Push Jerk',
    complexity: 2,
    musclesTargeted: [
      { name: 'coxa anterior', impact: 2 },
      { name: 'coxa posterior', impact: 2 },
      { name: 'ombro', impact: 4 },
      { name: 'gluteos', impact: 2 },
      { name: 'panturrilha', impact: 2 },
      { name: 'triceps', impact: 3 },
      { name: 'abdominal', impact: 1 },
      // { name: "cardio", impact: 3 },
      { name: 'costas inferior', impact: 2 },
    ],
    timePerRepInS: 2.5,
    blocks: ['Skill', 'WOD'],
  },
  55: {
    id: 55,
    name: 'Split Jerk',
    complexity: 3,
    musclesTargeted: [
      { name: 'coxa anterior', impact: 2 },
      { name: 'coxa posterior', impact: 2 },
      { name: 'ombro', impact: 4 },
      { name: 'triceps', impact: 2 },
      { name: 'abdominal', impact: 1 },
      { name: 'gluteos', impact: 2 },
      // { name: "cardio", impact: 3 },
      { name: 'costas inferior', impact: 2 },
    ],
    timePerRepInS: 2.5,
    blocks: ['Skill', 'WOD'],
  },
  56: {
    id: 56,
    name: 'Snatch',
    complexity: 4,
    musclesTargeted: [
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 2 },
      { name: 'costas superior', impact: 2 },
      { name: 'ombro', impact: 2 },
      { name: 'gluteos', impact: 3 },
      // { name: "cardio", impact: 4 },
      { name: 'costas inferior', impact: 3 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD'],
  },
  // 57: {
  //   id: 57,
  //   name: "Squat Snatch",
  //   complexity: 4,

  //   musclesTargeted: [
  // //     { name: "cardio", impact: 4 },
  //     { name: "coxa anterior", impact: 5 },
  //     { name: "coxa posterior", impact: 3 },
  //     { name: "costas superior", impact: 2 },
  //     { name: "shoulder", impact: 5 },
  //     { name: "triceps", impact: 2 },
  //     { name: "abs", impact: 1 },
  //   ],
  //   timePerRepInS: 3.5,
  //   blocks: ["WOD", "Skill"],
  // },
  58: {
    id: 58,
    name: 'Hang Snatch',
    complexity: 3,

    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 2 },
      { name: 'costas superior', impact: 2 },
      { name: 'ombro', impact: 2 },
      { name: 'costas inferior', impact: 2 },

      { name: 'abdominal', impact: 1 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD', 'Skill'],
  },
  59: {
    id: 59,
    name: 'Power Balance',
    complexity: 3,

    musclesTargeted: [
      // { name: "cardio", impact: 3 },
      { name: 'coxa anterior', impact: 2 },
      { name: 'coxa posterior', impact: 2 },
      { name: 'costas superior', impact: 2 },
      { name: 'costas inferior', impact: 3 },
      { name: 'ombro', impact: 1 },
    ],
    timePerRepInS: 4,
    blocks: ['WOD', 'Skill'],
  },
  60: {
    id: 60,
    name: 'Snatch Balance',
    complexity: 4,

    musclesTargeted: [
      { name: 'coxa anterior', impact: 4 },
      { name: 'coxa posterior', impact: 2 },
      { name: 'costas superior', impact: 2 },
      { name: 'ombro', impact: 2 },
      { name: 'gluteos', impact: 3 },
      // { name: "cardio", impact: 4 },
      { name: 'costas inferior', impact: 3 },
    ],
    timePerRepInS: 5,
    blocks: ['WOD', 'Skill'],
  },
  61: {
    id: 61,
    name: 'Run',
    complexity: 1,

    musclesTargeted: [
      // { name: "cardio", impact: 4 },
      { name: 'coxa anterior', impact: 1 },
      { name: 'gluteos', impact: 1 },
      { name: 'abdominal', impact: 1 },
    ],
    timePerRepInS: 0.5,
    blocks: ['Warm Up', 'WOD'],
  },
  62: {
    id: 62,
    name: 'Burpees',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 5 },
      { name: 'coxa anterior', impact: 4 },
      { name: 'costas inferior', impact: 2 },
      { name: 'peito', impact: 3 },
      { name: 'triceps', impact: 2 },
    ],
    timePerRepInS: 3,
    blocks: ['WOD'],
  },
  63: {
    id: 63,
    name: 'Double Unders',
    complexity: 5,
    musclesTargeted: [
      // { name: "cardio", impact: 5 },
      { name: 'panturrilha', impact: 3 },
      { name: 'ombro', impact: 2 },
      { name: 'abdominal', impact: 1 },
    ],
    timePerRepInS: 1,
    blocks: ['Skill', 'WOD'],
  },
  64: {
    id: 64,
    name: 'Bike',
    complexity: 1,
    musclesTargeted: [
      // { name: "cardio", impact: 5 },
      { name: 'coxa anterior', impact: 2 },
      { name: 'coxa posterior', impact: 2 },
      { name: 'abdominal', impact: 2 },
    ],
    timePerRepInS: 0.5,
    blocks: ['Warm Up', 'WOD'],
  },
  65: {
    id: 65,
    name: 'Rowing',
    complexity: 2,
    musclesTargeted: [
      // { name: "cardio", impact: 5 },
      { name: 'coxa posterior', impact: 2 },
      { name: 'costas superior', impact: 3 },
      { name: 'costas inferior', impact: 3 },
      { name: 'abdominal', impact: 1 },
    ],
    timePerRepInS: 2,
    blocks: ['WOD', 'Skill'],
  },
  66: {
    id: 66,
    name: 'Sprawl',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 5 },
      { name: 'coxa anterior', impact: 3 },
      { name: 'costas inferior', impact: 2 },
      { name: 'peito', impact: 2 },
      { name: 'triceps', impact: 1 },
    ],
    timePerRepInS: 3,
    blocks: ['Warm Up'],
  },

  67: {
    id: 67,
    name: 'Crab Toe Touch',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 5 },
      { name: 'coxa anterior', impact: 3 },
      { name: 'coxa posterior', impact: 2 },
      { name: 'gluteos', impact: 2 },
      { name: 'abdominal', impact: 2 },
    ],
    timePerRepInS: 1.5,
    blocks: ['Warm Up'],
  },

  68: {
    id: 68,
    name: 'Shoulder Taps',
    complexity: 3,
    musclesTargeted: [
      // { name: "cardio", impact: 5 },
      { name: 'ombro', impact: 3 },
      { name: 'abdominal', impact: 3 },
      { name: 'triceps', impact: 1 },
      { name: 'costas superior', impact: 1 },
      { name: 'costas inferior', impact: 1 },
    ],
    timePerRepInS: 1.5,
    blocks: ['Warm Up'],
  },
};
